### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by hlascelles** [target/pod-reaper#60]
Is there a desire for a helm chart for this? Even just a folder in the main repo which can be referred to.

And... has anyone done that work already?

**Comment by brianberzins** [comment]
I can't speak for everyone, but I've generally just deployed direct kubernetes manifest files in the past. I don't know if anyone has ever created a helm chart it. I'm certainly not against it, but also haven't played with helm since the much anticipated release of Helm 3!

Would love to hear from others on this!

**Comment by Bryce-L** [comment]
I'd love a helm chart.  Maybe it's because I'm new to Kubernetes, but after reading the ReadMe I still don't understand how to install this.  I'm sure I just need to learn more, but I do know how to use a helm chart.  I think a helm chart would lower the barrier of entry for an awesome tool like this.

**Comment by brianberzins** [comment]
I think that's valid critism of the readme! Looking back over it I think it's making a number of assumptions regarding familiarity with specific parts of kubernetes.

Here's what I've been doing for testing locally, which hopefully will at least help you feel like you've got a way to play around.

I've been using a tool called KinD (kubernetes in docker): https://kind.sigs.k8s.io/

1. `kind create cluster` makes a cluster running locally on docker (I like starting locally because pod-reaper configurations can  be "dramatic"

```
murasaki:~/code/src/github.com/target/pod-reaper(master)$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
```

2. `kubectl apply -f examples/cluster-permissions.yml` deploys the example in it's entirety into the cluster kubectl is pointed at. Double check to make sure it's the local cluster to be extra safe!

```
murasaki:~/code/src/github.com/target/pod-reaper(master)$ kubectl apply -f examples/cluster-permissions.yml 
namespace/reaper created
serviceaccount/pod-reaper-service-account created
clusterrole.rbac.authorization.k8s.io/pod-reaper-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/pod-reaper-role-binding created
deployment.apps/pod-reaper created
```

That's it. It's deployed. I then usually do a couple to watch it work. You can check the logs of the pod-reaper containers to see what actions it's taking, but I also usually do a `watch kubectl get pods -A` to see pods being deleted and recovering. In that example, pod-reaper will be looking at pods every 15 seconds and will kill about 5% of them (technically each pod has a 5% chance of being killed every 15 seconds). 

```
murasaki:~/code/src/github.com/target/pod-reaper(master)$ kubectl get pods -A
NAMESPACE            NAME                                         READY   STATUS        RESTARTS   AGE
kube-system          coredns-6955765f44-cgf2v                     1/1     Running       0          11m
kube-system          coredns-6955765f44-f8wbc                     0/1     Running       0          3s
kube-system          coredns-6955765f44-vvz7s                     1/1     Terminating   0          11m
kube-system          etcd-kind-control-plane                      1/1     Running       0          11m
kube-system          kindnet-2fjsg                                1/1     Running       0          11m
kube-system          kube-apiserver-kind-control-plane            1/1     Running       0          11m
kube-system          kube-controller-manager-kind-control-plane   1/1     Running       0          11m
kube-system          kube-proxy-gm8bk                             1/1     Running       0          11m
kube-system          kube-scheduler-kind-control-plane            1/1     Running       0          11m
local-path-storage   local-path-provisioner-7745554f7f-rj5lr      1/1     Running       0          11m
reaper               pod-reaper-66d5c85584-tg9kg                  1/1     Running       0          2m36s
```

^ here the kind cluster was up for 11 minutes or so, with the reaper being deployed only a couple minutes ago. Here it's showing it knocked out one of the coredns pods that KinD had (and shows that it's spinning up another to recover!)

If nothing else, I hope this can help you play around with this locally. I'm certainly no helm expect, but maybe it'd be cool to have :-)

**Comment by hlascelles** [comment]
Done! https://github.com/target/pod-reaper/pull/61

**Comment by hlascelles** [comment]
That PR was merged some time ago...
